services:
  postgres:
    image: postgres:15
    container_name: nvd_postgres
    restart: always
    environment:
      POSTGRES_USER: nvd
      POSTGRES_PASSWORD: secure_passwordlol
      POSTGRES_DB: nvd
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nvd_backend
    restart: always
    depends_on:
      - postgres
    environment:
      PG_DB_HOST: postgres
      PG_DB_USER: nvd
      PG_DB_PASSWORD: secure_passwordlol
      PG_DB_NAME: nvd
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nvd_frontend
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8000
    ports:
      - "3000:3000"

volumes:
  pg_data:
